### ISSUE TITLE
Why 31?

### ISSUE THREAD

**Issue by akriegman** [rtavenner/Hentriacontaphone#1]
Hi, this is the only way I could find to get in contact with you. I found you because I wanted to make a spherical geometry engine and your work is the closest thing on the internet to what I wanted to make. By sheer luck, your hentriacontaphone was so similar to an instrument I wanted to make that I just had to change a couple lines of code. You can check out my fork. I'm wondering, why did you choose 31 ET?

**Comment by rtavenner** [comment]
### Why 31?

Since your fork is about Just Intonation, I assume you know that rational frequency ratios create nice musical intervals. So a good equal temperament is one where simple rational ratios are well-approximated by integer numbers of scale steps.

Eighteen steps of 31-ET create a frequency ratio of 2^(18/31) = 1.4955, which is somewhat close to 3/2. This is actually worse than seven steps of 12-ET, with frequency ratio 1.4983.

However...
Ten steps of 31-ET create a frequency ratio of 2^(10/31) = 1.2506, which is really close to 5/4. This is much better than four steps of 12-ET, with frequency ratio 1.2599.

Twenty-five steps of 31-ET create a frequency ratio of 2^(25/31) = 1.7489, which is really close to 7/4. This is much better than ten steps of 12-ET, with frequency ratio 1.7818.

There's some interesting math that relates the list of good equal temperaments to the Riemann Zeta function. If you're interested, you can find an article on that [here](https://en.xen.wiki/w/The_Riemann_Zeta_Function_and_Tuning). If not, you basically find that the best tunings are 12-, 19-, 31-, 53-, and 72-ET.

My project was also inspired by the [Fokker Organ](https://en.wikipedia.org/wiki/Adriaan_Fokker#Musical_instruments), a 31-ET organ.

### Spherical Geometry

You mention you want to work with spherical geometry. Here's a free tutorial.

Suppose you create a Euclidean renderer, using OpenGL.
Your vertex shader will probably look something like this:
```
in vec3 pos;

uniform mat4 transform;
uniform mat4 perspective;

void main() {
    gl_Position = perspective * transform * vec4(pos, 1.0);
}
```

For spherical geometry, you can do nearly the same thing:
```
// x*x + y*y + z*z + w*w == 1.0
in vec4 pos;

uniform mat4 transform;
uniform mat4 perspective;

void main() {
    gl_Position = perspective * transform * pos;
}
```

But the `transform` and `perspective` matrices take slightly different forms.

In Euclidean space, when you move forward `z` units, `transform` is multiplied on the left by this matrix:
```
⎡1 0 0 0⎤
⎢0 1 0 0⎥
⎢0 0 1 z⎥
⎣0 0 0 1⎦
```

In spherical space, use this matrix instead:
```
⎡1 0      0      0 ⎤
⎢0 1      0      0 ⎥
⎢0 0  cos(z) sin(z)⎥
⎣0 0 -sin(z) cos(z)⎦
```

As for `perspective`, you just have to replace the `z_near` and `z_far` values in its formula with `tan(z_near)` and `tan(z_far)`.
This will work for `z_far < π`. If you want a view distance larger than `π`, I suggest doing two render passes.

When I wrote my projects, I assumed this would only work for `z_far < π/2`, so I implemented a workaround to increase it to `π`. I now realize that that was entirely unnecessary, and the workaround caused problems, so I don't recommend it.

A similar method also works for hyperbolic geometry. But there, floating point precision limits are a *much* larger issue, and will need to be dealt with somehow.

Implementing spherical geometry might seem surprisingly simple. But OpenGL really works with projective 3-space, from which both Euclidean and spherical geometry can be obtained. So OpenGL is just as suited to spherical geometry as Euclidean.

**Comment by akriegman** [comment]
Hey, I just saw your response. That's really cool about 31 ET, I had no idea. I had figured 41 ET would be better since 24/41 is the next convergent of log2(3/2), but iirc the major third in 41 ET is pretty bad.

I actually just this week started working on my spherical geometry game in Unity. My scheme is to use a single 4D rotation to capture both the position and orientation of an object, and then to represent 4D rotations using isoclinic decomposition with quaternions (https://en.wikipedia.org/wiki/Rotations_in_4-dimensional_Euclidean_space#Relation_to_quaternions). There's a lot of advantages to using quaternions, for example it's really easy to interpolate between rotations, and I found a nice formula for small rotations when moving. I also opted to just use the default Unity projection matrix, which is working fine so far lol.

We should switch to email so we don't have to keep talking through the GitHub issues. My email is aaronkplus2@gmail.com
